experiment_name: smoke
log_dir: ./experiments
train_data_path: /datasets/extra_space2/rpartsey/3d-navigation/habitat/data/map_pose_correction/preprocessed_data/train
val_data_path: /datasets/extra_space2/rpartsey/3d-navigation/habitat/data/map_pose_correction/preprocessed_data/val
num_workers: 2
train_batch_size: 32
val_batch_size: 32
epochs: 128
device: cuda:2
lr: 0.0001
seed: 1
log_interval: 1
save_model: False